### ISSUE TITLE
Scanning function 

### ISSUE THREAD

**Issue by shwetaparihar** [ljm7b2/ASE_PROJECT_G1#16]
Implementation of Scanning function
<img width="220" alt="scan" src="https://cloud.githubusercontent.com/assets/9245443/13183722/f3ab8d4e-d6fd-11e5-8a18-55e44ee69ed2.PNG">

**Comment by ljm7b2** [comment]
An Idea for this is to have a listview that pulls the content from the DB. Once an item from the listview is selected, the view expands and the above wireframe is used.
